# Tensors

In [2]:
import torch
import numpy as np

## Tensors initialization

By default, tensors are created on the CPU. We can specify the device which we want to use by default:

In [30]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

In [31]:
tensor = torch.tensor(data=[[1, 2, 3], [4, 5, 6]],
                      dtype=torch.float32,
                      device=DEVICE)

Move manually to the GPU:

In [29]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

Other ways to create tensors:

In [41]:
# Directly from data
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)

# From a NumPy array
np_array = np.array([[1, 2], [3, 4]])
np_tensor = torch.from_numpy(np_array)

# From antoher tensor (usually, the name of the tensor finished in _like)
ones_tensor = torch.ones_like(data_tensor)

# With random or constant values
shape = (2, 3,)
rand_tensor = torch.rand(shape) # uniform distribution in the interval 0 to 1
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [42]:
# same as torch.diag(torch.ones(3))
torch.eye(3) # I (pronounced 'eye')

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
torch.arange(start=0, end=5, step=1)

tensor([0, 1, 2, 3, 4])

In [45]:
torch.linspace(start=0, end=10, steps=3)

tensor([ 0.,  5., 10.])

In [46]:
# torch.empty -> Unitialized data (they're not 0s -> Only if you print it, it'll print 0s)
empty_tensor = torch.empty(shape)

# This will make the values normally distributed with mean 0 & standard deviation 1
empty_tensor.normal_(mean=0, std=1) # we can also use other methods like uniform_

tensor([[ 1.2452,  0.1908, -1.0599],
        [-0.2631,  1.3604, -0.0380]])

## Attributes of a Tensor

In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Change the data type of a tensor

In [49]:
tensor = torch.arange(6)
print(tensor)

tensor([0, 1, 2, 3, 4, 5])


In [50]:
tensor.bool()

tensor([False,  True,  True,  True,  True,  True])

In [51]:
# tensor.short() <- equivalent to tensor.to(torch.int16)
# tensor.long()  <- equivalent to tensor.to(torch.int64)
# tensor.half()  <- equivalent to tensor.to(torch.float16) <- Need GPU with a version >= 2000
# tensor.float() <- equivalent to tensor.to(torch.float32)
# tensor.double() <- equivalent to tensor.to(torch.float64)

## Operations on Tensors

List of the operations: [PyTorch Operations](https://pytorch.org/docs/stable/torch.html)

### Concatenation

If you're not familiar with the dim attribute, I print below some examples using different values of the dim attribute. But to summarize:
- `dim=0`: Append to the x-axis (as rows)
- `dim=1`: Append to the y-axis (as columns)
- `dim=-1`: Append to the last dimension possible. In a 2D matrix, dim=1 == dim=-1

In [15]:
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

cat_tensor_dim_0 = torch.cat(tensors=[tensor1, tensor2, tensor1], dim=0)
print("Dim=0 (x-axis):", cat_tensor_dim_0, sep='\n', end='\n\n')

cat_tensor_dim_1 = torch.cat(tensors=[tensor1, tensor2, tensor1], dim=1)
print("Dim=1 (y-axis):", cat_tensor_dim_1, sep='\n')

Dim=0 (x-axis):
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [ 1,  2,  3],
        [ 4,  5,  6]])

Dim=1 (y-axis):
tensor([[ 1,  2,  3,  7,  8,  9,  1,  2,  3],
        [ 4,  5,  6, 10, 11, 12,  4,  5,  6]])


### Arithmetic operations

Addition:

In [53]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [54]:
# All these options are equivalent
add_result_1 = x + y
add_result_2 = torch.add(x, y)
add_result_3 = torch.empty(3)
torch.add(x, y, out=add_result_3)

tensor([5., 7., 9.])

Subtraction:

In [58]:
sub_result_1 = x - y
sub_result_2 = torch.sub(x, y)
sub_result_3 = torch.empty(3)
torch.sub(x, y, out=sub_result_3)

tensor([-3., -3., -3.])

Division:

In [59]:
# rounding_mode:
# - None: Performs no rounding <- equivalent to np.true_divide
# - "trunc": Truncates the result
# - "floor": Rounds the result of the division down (same as // python operator)
torch.div(x, y, rounding_mode=None)

tensor([0.2500, 0.4000, 0.5000])

Exponentiation:

In [67]:
pow_result_1 = x.pow(2)
pow_result_2 = x ** 2

# Matrix exponentiation
matrix_exp = torch.randint(low=1, high=5, size=(3, 3,))
print(matrix_exp)
print(matrix_exp.matrix_power(3))

tensor([[4, 3, 4],
        [3, 4, 2],
        [3, 2, 3]])
tensor([[346, 307, 314],
        [285, 258, 256],
        [252, 223, 229]])


Matrix multiplication & element-wise product:

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
# Matrix multiplication between two tensors (@ and matmul have the same use)
mul_result_1 = tensor @ tensor.T
mul_result_2 = tensor.matmul(tensor.T) # equivalent to torch.mm
mul_result_3 = torch.ones_like(tensor)
torch.matmul(input=tensor, other=tensor.T, out=mul_result_3)

# Element-wise product (* and mul have the same use)
ew_result_1 = tensor * tensor
ew_result_2 = tensor.mul(tensor) 
ew_result_3 = torch.ones_like(tensor)
torch.mul(input=tensor, other=tensor, out=ew_result_3)

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [ ]:
# Dot product: torch.dot(x, y)

Batch matrix multiplication (BMM):

In [68]:
batch = 16
n = 10
m = 20
p = 30

In [69]:
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p) shape

Inplace operations (they're denoted by an underscore _ at the end):

In [61]:
t = torch.zeros(3)
t.add_(5) # computationally efficient

tensor([5., 5., 5.])

Element-wise comparison:

In [63]:
rand_tensor = torch.rand(5)
print(rand_tensor)

tensor([0.9313, 0.4698, 0.5707, 0.4373, 0.9755])


In [64]:
z = rand_tensor > 0.5
print(z)

tensor([ True, False,  True, False,  True])


Broadcasting (expanding the dimension of a tensor automatically to perform the operation):

In [ ]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2 # x1[0] - x2, x1[1] - x2, x1[2] - x2, etc.

Clamp (set all elements that satisfy a condition (be less than the min or greater than the max, for example), to 0):

In [91]:
x = torch.tensor([-5, 4, -3, 6, 7])
torch.clamp(x, min=0)

tensor([0, 4, 0, 6, 7])

Logic operators (any, all):

In [97]:
w = torch.tensor([0, 3, 4, 8, 10]) # same as [False, True, True, True, True] in boolean

In [98]:
torch.any(w)

tensor(True)

In [99]:
torch.all(w)

tensor(False)

In [3]:
x = torch.arange(10)

In [4]:
# Pick all that are, or less than 2 or greater than 8
print(x[(x < 2) | (x > 8)])

tensor([0, 1, 9])


In [5]:
print(x[x.remainder(2) == 0])

tensor([0, 2, 4, 6, 8])


In [6]:
# if x[i] is not greater than 5, we're going to return x[i] * 2
torch.where(condition=x>5, input=x, other=x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

Other useful tensor operations:

In [88]:
x = torch.tensor([1, 2, 4, 4])
y = torch.tensor([1, 5, 6, 8])

In [89]:
torch.sum(x) # equivalent to x.sum(dim=0)

tensor(11)

In [90]:
torch.abs(x) # equivalent to x.abs()

tensor([1, 2, 4, 4])

In [76]:
values, indices = torch.min(x, dim=0) # equivalent to x.min(dim=0)
values, indices = torch.max(x, dim=0) # equivalent to x.max(dim=0)
print(values, indices)

tensor(4) tensor(2)


In [100]:
z_idx = torch.argmin(x, dim=0) # equivalent to x.argmin(dim=0)

# It just prints the index of the greatest element
z_idx = torch.argmax(x, dim=0) # equivalent to x.argmax(dim=0)
print(z_idx)

tensor(4)


In [82]:
# The mean requires x to be float
torch.mean(x.float(), dim=0)


tensor(2.7500)

In [85]:
# Check if they're equal
torch.eq(x, y)

tensor([ True, False, False, False])

In [87]:
values, indices = torch.sort(y, dim=0, descending=False)

In [8]:
# To get the unique values of a tensor, use .unique()
x = torch.tensor([0, 0, 0, 1, 2, 3, 3, 4])
x.unique()

tensor([0, 1, 2, 3, 4])

In [ ]:
# x.ndimension() <- count the number of dimensions
# x.numel()      <- count the number of elements

## Reshaping, Flattening, Permuting, ...

### Reshape

In [11]:
x = torch.arange(1, 10)
print(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


Convert the tensor into a 3x3 matrix:

In [12]:
x.view(3, 3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
x.reshape(3, 3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

⚠️ There are differences between the way view and reshape work, so be careful!

view stores the matrix contiguously in memory. It can be a more efficient, but it can lead to some errors also. So, as a safe bet, use reshape.

### Flatten

In [17]:
x = torch.randint(1, 9, (2, 5))
print(x)

tensor([[2, 1, 7, 6, 6],
        [1, 6, 3, 7, 4]])


In [18]:
# Use it to flatten the matrix
x.view(-1)

tensor([2, 1, 7, 6, 6, 1, 6, 3, 7, 4])

In [21]:
# And, in the case that we want to flatten it conserving the batches:
batch = 64
x = torch.rand((batch, 2, 5))
print(x.shape)
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 2, 5])
torch.Size([64, 10])


### Permuting

The permutation consists on changing the dimensions of a tensor manually.

For example, say you have a tensor with shape [64, 2, 5].

tensor.permute(0, 2, 1) can be read as:
- For the dimension 0, change it to dimension 0 (leaving as it is).
- For the dimension 1, introduce in this dimension the second one.
- For the dimension 3, introduce in this dimension the first one.

So the output will be of shape [64, 5, 2]

In [27]:
x = torch.randint(1, 9, (64, 2, 5))
print(x.shape)

torch.Size([64, 2, 5])


In [29]:
x.permute(0, 2, 1).shape

torch.Size([64, 5, 2])

### Unsqueeze

Add a dimension indicated as an argument to the unsqueeze method

In [30]:
x = torch.arange(10)
print(x.shape)

torch.Size([10])


In [33]:
# Add a dimension at the beginning
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


## Bridge with NumPy

⚠️ Be careful, a change in a tensor affects also to the numpy array (and viceversa)

In [25]:
# Tensor -> NumPY
tensor = torch.ones(5)
np_array = tensor.numpy()
print(tensor, np_array, sep='\n')

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [26]:
# See what happens when we sum 5 to every element of the tensor:
tensor.add_(5)
print(tensor, np_array, sep='\n')

tensor([6., 6., 6., 6., 6.])
[6. 6. 6. 6. 6.]


In [27]:
# NumPy -> Tensor
np_array = np.ones(10)
tensor = torch.from_numpy(np_array)

In [28]:
# Same happens
np_array += 3
print(tensor, np_array, sep='\n')

tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.], dtype=torch.float64)
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
